[workspace]
authors = ["Safe Gergis <safegerg@gmail.com>"]
channels = ["conda-forge"]
name = "context-magnifier"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
pygobject = ">=3.50.0,<4"
cmake = ">=4.0.1,<5"
face_recognition = ">=1.3.0,<2"
