[workspace]
authors = ["Safe Gergis <safegerg@gmail.com>"]
channels = ["conda-forge"]
name = "context-magnifier"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
pygobject = ">=3.50.0,<4"
cmake = ">=4.0.1,<5"
face_recognition = ">=1.3.0,<2"
pyside6 = ">=6.9.0,<7"
pytesseract = ">=0.3.13,<0.4"
numpy = ">=2.2.4,<3"
pillow = ">=11.1.0,<12"
opencv = ">=4.11.0,<5"
matplotlib = ">=3.10.1,<4"

[pypi-dependencies]
pyqt5 = ">=5.15.11, <6"
pyautogui = ">=0.9.54, <0.10"
